hw2-express
vladislaviwe/nodejs-homework-rest-api pull request #1
Opened 2023-01-31 18:46 UTC by vladislaviwe

Task completed

2023-01-31 20:54 UTC, Eastvarga requested changes
Є зауваження

2023-01-31 20:54 UTC, Eastvarga commented on models/contacts.js
> +    }
це зайве, ця умова частина валідації, коли схема вірна цей код ніколи у Вас не виконається - приберіть це

2023-01-31 20:54 UTC, Eastvarga commented on models/contacts.js
> +    return contacts[index];
спробуйте не використовувати методи котрі мутують масив.
також зробіть цей метод більш універсальним - коли в метод потрапить data лише з одним полем - щоб решта не щезла з оновленого контакту

2023-02-01 19:09 UTC, vladislaviwe commented on models/contacts.js
> +    return contacts[index];
Там виправлю, щоб мутації не було. В мене стоїть перевірка, щоб приходило 3 поля, тобто не можна відправити дані з одним заповненим полем. Мені треба зробити так, щоб можна було змінити лише одне поле, чи що ви маєте на увазі?

2023-02-01 19:10 UTC, vladislaviwe commented on models/contacts.js
> +    }
Приберу, не помітив, з минулого д/з залишилось.

2023-02-12 09:02 UTC, Eastvarga commented on models/contacts.js
> +    return contacts[index];
Сам метод Ваш має бути універсальним, він має оновити об'єкт тими даними що прийдуть у нього і не важливо чи прийдуть всі поля чи ні - тоді його можна перевикористати,він буде відповідати свойому функціоналу (оновлення контакту), та він не буде з'язаним з попередніми умовами о котрих він не повинен знати.
Прийшлі данні, він відповідно їм оновив об'єкт, будь там одн чи всі поля.

2023-02-12 09:05 UTC, Eastvarga approved these changes
Є погана реалізація оновлення контакуту.

2023-02-12 09:05 UTC, Eastvarga commented on models/contacts.js
> +    contacts.push(newContact);
Це дуже погана логіка, практикуйте методи масивів, та навчіться оновлювати елемент під час виконання методу масиву (map)

2023-02-12 09:06 UTC, merged